application: appengfun
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- remote_api: on

handlers:
- url: /js
  static_dir: js
- url: /images
  static_dir: images
- url: /_ah/login_required
  script: do_openid_login.py
- url: /api/authorize
  script: api.py
  login: required
- url: /api/.*
  script: api.py
  secure: always
- url: .*
  script: main.py
  login: required
